### ISSUE TITLE
Issues related to Night Mode

### ISSUE THREAD

**Issue by brainwo** [ambinusian/adab#3]
Night mode doesn't work well on:
- Calendar Fragment
- Account Details
- Mode Toggle Button

**Comment by developerchan1** [comment]
Let me fix that problem

**Comment by brainwo** [comment]
I thought we no longer use this

**Comment by developerchan1** [comment]
So we just need to remove the night mode?

**Comment by brainwo** [comment]
Since we already make the web version responsive, could you help me turn this into WebView app instead?
![image](https://user-images.githubusercontent.com/45139213/87848721-08f12280-c90d-11ea-8986-637d0c8a67cd.png)

**Comment by brainwo** [comment]
It will be less maintenance for us

**Comment by developerchan1** [comment]
Ehhmm, I think we should discuss that with the others first

**Comment by werdna521** [comment]
Hi, how's the progress on this issue?

**Comment by developerchan1** [comment]
Still fix the issues

**Comment by brianrahula** [comment]
#5
